.\"                                      Hey, EMACS: -*- nroff -*-
.TH MAKEPAGE 1 "January  2, 2011"
.SH NAME
makepage \- convert markdown input to a fully-formed xhtml page
.SH SYNOPSIS
.SY mkd2html
.RI [ file ]
.SH DESCRIPTION
\fBmakepage\fP parses a markdown input file and prints to stdout a
fully-formed xhtml page.

\fBmakepage\fP is part of discount.
.Sh SEE ALSO
.Xr markdown 1 ,
.Xr markdown 3 ,
.Xr markdown 7 ,
.Xr mkd-extensions 7 .
.Sh AUTHOR
.An David Parsons
.Pq Li orc@pell.chi.il.us
