.\"                                      Hey, EMACS: -*- nroff -*-
.TH MKD2HTML 1 "January  2, 2011"
.SH NAME
mkd2html \- markdown to html converter
.SH SYNOPSIS
.SY mkd2html
.OP \-css file
.OP \-header string
.OP \-footer string
.RI [ file ]
.SH DESCRIPTION
\fBmkd2html\fP parses a markdown input file and generate a web page. It
reads file or file.text and writes the result in file.html (where file is
the passed argument).

\fBmkd2html\fP is part of discount.
.SH OPTIONS
.TP
.B \-css file
Specifies a CSS file.
.TP
.B \-header string
Specifies line to add to the <HEADER> tag.
.TP
.B \-footer string
Specifies line to add to the before the <\/BODY> tag.
.Sh SEE ALSO
.Xr markdown 1 ,
.Xr markdown 3 ,
.Xr markdown 7 ,
.Xr mkd-extensions 7 .
.Sh AUTHOR
.An David Parsons
.Pq Li orc@pell.chi.il.us
